repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
          - -p
          - trustforge
        pass_filenames: false
        additional_dependencies:
          - pydantic>=2.6
          - jinja2>=3.1
          - markdown-it-py>=3.0
          - typer>=0.12
          - types-PyYAML

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
