# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Create venv
        run: uv venv

      - name: Install project + tooling
        run: |
          uv pip install -e .
          uv pip install ruff mypy pytest types-PyYAML

      - name: Lint
        run: uv run ruff check .

      - name: Type check
        run: uv run mypy -p trustforge

      - name: Tests
        run: PYTHONPATH=src uv run pytest

      - name: HTML smoke build
        run: PYTHONPATH=src uv run trustforge html policies/information-security-policy.md
# PDF Verification
  pdf_release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip uv
      - run: uv venv
      - run: uv pip install -e .
      - name: Install TeX Live (minimal)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-latex-recommended texlive-latex-extra
      - name: Build PDF
        run: uv run trustforge pdf policies/information-security-policy.md
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: policy-pdf
          path: out/*.pdf
