name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.13']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Create venv
        run: uv venv

      - name: Install project
        run: |
          uv pip install -e .
          # toolchain used by CI
          uv pip install ruff mypy pytest types-PyYAML

      - name: Lint
        run: uv run ruff check .

      - name: Type check
        run: uv run mypy -p trustforge

      - name: Tests
        run: uv run pytest -q

      - name: HTML smoke build
        run: uv run trustforge html policies/information-security-policy.md
